### ISSUE TITLE
example 3nic byol failover contains wrong gateway for internalIntRoute

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates-v2#14]
## Describe the bug
 
Example yaml runtime init has incorrect gateway for the internalIntRoute
 
## Expected behavior
 
Gateway should be internal gateway.
 
## Current behavior
 
External gateway is used in yaml and does not exist in internal network...fails.
 
## Possible solution
 
https://github.com/F5Networks/f5-google-gdm-templates-v2/blob/main/examples/failover/bigip-configurations/runtime-init-conf-3nic-payg-instance01.yaml
Current code block...
```
          internalIntRoute:
            class: Route
            gw: '{{{EXTERNAL_GW}}}'
            network: '{{{INTERNAL_NETWORK}}}/{{{INTERNAL_BITMASK}}}'
            mtu: 1460
```

Needs to be like 02 device.
https://github.com/F5Networks/f5-google-gdm-templates-v2/blob/main/examples/failover/bigip-configurations/runtime-init-conf-3nic-payg-instance02.yaml
```
          internalIntRoute:
            class: Route
            gw: '{{{INTERNAL_GW}}}'
            network: '{{{INTERNAL_NETWORK}}}/{{{INTERNAL_BITMASK}}}'
            mtu: 1460
```
 
Please check all example files.

## Steps to reproduce
 
n/a
